# This file was generated by GoReleaser. DO NOT EDIT.
cask "clishake" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "b3fa43b1e1e28e6a747048488a8ce3d748b664477110c6fc85f1d6a331e68171"
      url "https://github.com/Clishakehq/CLIshake/releases/download/v#{version}/clishake_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2935fa5f9aaa333bbc461a55da868084f660b3e8113a179571b960e36b526f90"
      url "https://github.com/Clishakehq/CLIshake/releases/download/v#{version}/clishake_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "30a586aea226527d3daf83a96cc342b2553c4735a65dcae4e5eb44a78c36e55e"
      url "https://github.com/Clishakehq/CLIshake/releases/download/v#{version}/clishake_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "04c96964955a3d90dc07596817f1978c14cbe4b26ad67e437b3a40ad6356beeb"
      url "https://github.com/Clishakehq/CLIshake/releases/download/v#{version}/clishake_#{version}_linux_arm64.tar.gz"
    end
  end

  name "clishake"
  desc "The terminal coordination layer for collaborating coding agents"
  homepage "https://clishake.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clishake"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/clishake"]
    end
  end

  # No zap stanza required

end
