# This file was generated by GoReleaser. DO NOT EDIT.
cask "clishake" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "72508e3a88b1982433b92fa7d73de743e75abcf911ccfca0a7ca665360757c0a"
      url "https://github.com/Clishakehq/CLIshake/releases/download/v#{version}/clishake_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7f1a88feab6128e732a4e45a2ce8cf4da1ccaac0d2c98d3877d8aa6f76e8de34"
      url "https://github.com/Clishakehq/CLIshake/releases/download/v#{version}/clishake_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b6f0c42fdab4c74c439e0b235d75e0e540edbac86845ead9bad4a9ee5501bf23"
      url "https://github.com/Clishakehq/CLIshake/releases/download/v#{version}/clishake_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a99c100e2cf7db8930d1d39275fed5822b0516ed8af8053db57ebc83088b7f1f"
      url "https://github.com/Clishakehq/CLIshake/releases/download/v#{version}/clishake_#{version}_linux_arm64.tar.gz"
    end
  end

  name "clishake"
  desc "The terminal coordination layer for collaborating coding agents"
  homepage "https://clishake.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clishake"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/clishake"]
    end
  end

  # No zap stanza required

end
